apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJHRVQgVEhJUyBGUk9NIFFVQVkgQVMgQSByZWdpc3RyeSBhdXRoIGZvcm1hdCIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
kind: Secret
metadata:
  creationTimestamp: null
  name: quay-cloudservices-pull
type: kubernetes.io/dockerconfigjson
