apiVersion: cloud.redhat.com/v1alpha1
kind: Frontend
metadata:
  name: chrome
spec:
  # Add fields here
  envName: env-boot
  title: Chrome
  deploymentRepo: https://github.com/RedHatInsights/insights-chrome/
  API:
    versions:
      - v1
  frontend:
    paths:
      - /
      - /apps/chrome
      - /config/chrome
  # testing, previous tag used was 4e0f158  - LIVE 
  image: quay.io/cloudservices/insights-chrome-frontend:720317c
  module:
    manifestLocation: "/apps/chrome/js/fed-mods.json"
    ssoUrl: https://keycloak-dev-sso.apps-crc.testing/auth
    config:
      ssoUrl: https://keycloak-dev-sso.apps-crc.testing/auth/
