apiVersion: cloud.redhat.com/v1alpha1
kind: FrontendEnvironment
metadata:
  name: env-boot
spec: 
# Use hack/update-sso.sh to compute this for dev-sso auth domain 
  sso: "https://keycloak-dev-sso.apps.hac-dev.clusters.stonesoupengineering.com/auth/" 
  ingressClass: openshift-default
  hostname: hac-dev.clusters.stonesoupengineering.com
